# Generated by Django 4.0.2 on 2024-04-06 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorproject',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tutorproject',
            name='tutor_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_projects', to='projects.exam'),
        ),
        migrations.AddField(
            model_name='tutorpledge',
            name='pledged_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporter_pledges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tutorpledge',
            name='pledged_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='projects.tutorproject'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='projects.exam'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='examinee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_exams', to=settings.AUTH_USER_MODEL),
        ),
    ]
